### ISSUE TITLE
work on windows os ?

### ISSUE THREAD

**Issue by mosi-kha** [ClearcodeHQ/pytest-elasticsearch#179]
hi,  is this library just work on **UNIX os**?
because in **windows os** I have this error :
`AttributeError: module 'select' has no attribute 'poll'` and `poll` just implemented in UNIX platforms.

**Comment by fizyk** [comment]
@mosi-kha could you create issue against https://github.com/ClearcodeHQ/mirakuru ? That's the library responsible for starting and managing processes. And we haven't been testing against windows.
Maybe if you'd use WSL it would work. But for now, Windows is not supported. (I'd welcome any maintainable contribution though).
