### ISSUE TITLE
Support using a custom elasticsearch configuration directory

### ISSUE THREAD

**Issue by fizyk** [ClearcodeHQ/pytest-elasticsearch#28]
_From @mmaslowskicc on June 17, 2015 12:38_

```
        command_exec = '''
            {deamon} -p {pidfile} --http.port={port}
            --path.home={home_path}  --default.path.logs={logs_path}
            --default.path.work={work_path}
            --default.path.conf=/etc/elasticsearch
[...]
```

So configuration is taken from the system-wide `/etc/elasticsearch` directory. This prevents packages using pytest-dbfixtures from using custom configuration included in their repositories, maintained via pull requests and used on CI where the test suite has no permission to write in `/etc`. (It can be useful to customize e.g. log verbosity for tests.)

_Copied from original issue: ClearcodeHQ/pytest-dbfixtures#122_

**Comment by fizyk** [comment]
_From @vcavel on June 28, 2016 14:22_

Do you have any updates on this?

**Comment by fizyk** [comment]
We'd gladly accept pull requests :)

**Comment by erewok** [comment]
You can also use `ES_JAVA_OPTS` to override default config path:

```
export ES_JAVA_OPTS="-Xms1g -Xmx1g -Des.path.conf=$path_config"
```
