### ISSUE TITLE
Elasticsearch version not recognized on Mac

### ISSUE THREAD

**Issue by konstantinmiller** [ClearcodeHQ/pytest-elasticsearch#303]
On my Mac, `elasticsearch -Vv` returns `Version: 7.12.0, Build: default/tar/78722783c38caa25a70982b5b042074cde5d3b3a/2021-03-18T06:17:15.410153305Z, JVM: 15.0.1`.

The `version` property in the `ElasticSearchExecutor` tries to parse that using 
```
match = re.search(
                    r'Version: (?P<major>\d)\.(?P<minor>\d)\.(?P<patch>\d+)',
                    output
                )
```
which fails.

**Comment by konstantinmiller** [comment]
Actually, the only problem is the missing `+` in the regex for the minor version. It should be

```
match = re.search(
    r'Version: (?P<major>\d)\.(?P<minor>\d+)\.(?P<patch>\d+)',
    output
)
```

**Comment by fizyk** [comment]
duplicates #301
