### ISSUE TITLE
elasticsearch_proc returns an executor not a fixture

### ISSUE THREAD

**Issue by konstantinmiller** [ClearcodeHQ/pytest-elasticsearch#326]
`factories.elasticsearch_proc` returns a fixture that gives an `ElasticSearchExecutor` object. Is that intended?

It this a different behavior than the `factories.elasticsearch` which creates a fixture that returns an `Elasticsearch` object directly.

What is the intended way to get an Elasticsearch instance from the executor inside the test? `factories.elasticsearch` does it by calling `client = Elasticsearch([{'host': process.host, 'port': process.port}])` but is it supposed to be called inside a test??

**Comment by fizyk** [comment]
@konstantinmiller yes, that's indended, first gets you running elasticsearch instance you can stop, or connect to yourself in any way you want, 2nd uses the process fixture to get exector, use connection details there and createa client you can connect to in tests.

But basically you don't really need to use elasticsearch_proc fixture to be used in tests, except if you want to test how your code will react if it lost the connection to the elasticsearch (ie, it got killed/stopped)

**Comment by konstantinmiller** [comment]
Ok, got it.

You need to use it if you want to customize the `Elasticsearch` path :)

**Comment by fizyk** [comment]
Or you can use the command line or .ini configuration file option instead https://github.com/ClearcodeHQ/pytest-elasticsearch#configuration :)
