### ISSUE TITLE
doesn't work with pytest7

### ISSUE THREAD

**Issue by ywietler** [ClearcodeHQ/pytest-elasticsearch#388]
### What action do you want to perform
I tried to update my projects dependencies for pytest from v6.25 to v7.0.1 but that lead to an ImportError for pytest-elasticsearch.

### What are the results
Updating pytest results in `ImportError: cannot import name 'TempdirFactory' from '_pytest.tmpdir'`
The [docs](https://docs.pytest.org/en/6.2.x/changelog.html) for pytest v6.2.0 marked the directly calling or construction for the TempdirFactory as deprecated.

### What are the expected results
It would be nice if pytest-elasticsearch would be usable after updating pytest to version 7.x

Thanks a lot

**Comment by fizyk** [comment]
Please check version 3.0.0

**Comment by fizyk** [comment]
Forgot to release these changes earlier

**Comment by ywietler** [comment]
Thanks for the fast reply! Everything works fine now!
