### ISSUE TITLE
4.0.0 is not compatible with elasticsearch<8

### ISSUE THREAD

**Issue by vincbon** [ClearcodeHQ/pytest-elasticsearch#512]
There is an issue running 4.0.0 with `elasticsearch<8`, as shown by:
```python
test setup failed
request = <SubRequest 'es_client' for <Function test_main>>

    @pytest.fixture
    def elasticsearch_fixture(request: FixtureRequest) -> Iterator[Elasticsearch]:
        """Elasticsearch client fixture."""
        process = request.getfixturevalue(process_fixture_name)
        if not process.running():
            process.start()
        client = Elasticsearch(
            hosts=[{"host": process.host, "port": process.port, "scheme": "http"}],
            request_timeout=30,
            verify_certs=False,
        )
>       client.options(ignore_status=400)
E       AttributeError: 'Elasticsearch' object has no attribute 'options'
```
The `options` attribute was added in version 8 of `elasticsearch`.

**Comment by fizyk** [comment]
Code line:
https://github.com/ClearcodeHQ/pytest-elasticsearch/pull/384/files#diff-f5db3c7f7a1894e48c35c7de3b9bb15ec1fb4b43573844b72b59557d847e900fR178

`elasticsearch=>8` allows to run tests only against Elasticsearch 7.17 if I recall correctly.

But an additional test run with elasticsearch<8 for that run on CI would be good to have.

**Comment by vincbon** [comment]
I'm having this issue with `elasticsearch==7.17.9` and `pytest-elasticsearch==4.0.0`.

**Comment by fizyk** [comment]
yeah, by `Elasticsearch 7.17` I meant the server, not library :)

**Comment by fizyk** [comment]
@vincbon 4.0.1 will be up in a short while
