### ISSUE TITLE
Test elastic above 8.0.0 on an existing server 

### ISSUE THREAD

**Issue by maxenva-ext** [ClearcodeHQ/pytest-elasticsearch#567]
### What action do you want to perform
There is 2 issue :
It looks like we can't connect pytest-elasticsearch with an elastic client above 8.0.0 on a server that already exist with the following line 
`es_client = factories.elasticsearch("elasticsearch_nooproc")`

Elastic client changed their way to connect with the [elastic-transport-python](https://github.com/elastic/elastic-transport-python) API and since there is the following error. 
`````python
ValueError: URL must include a 'scheme', 'host', and 'port' component (ie 'https://localhost:9200')
~/.local/lib/python3.10/site-packages/elastic_transport/client_utils.py:212: ValueError
`````

The second issue is smaller but when you use a toml file for configuration there is wrong type raised by [elastic-transport-python](https://github.com/elastic/elastic-transport-python) that raise this error. 
`````python  
`TypeError: '<' not supported between instances of 'str' and 'int'`
~/.local/lib/python3.10/site-packages/elastic_transport/_models.py:305: TypeError
`````
I've found a small (disgracious) work around in the factories.py file 
`````python factories.py
yield NoopElasticsearch(host=es_host, port=es_port) # master 
yield NoopElasticsearch(host=es_host, port=int(es_port)) # work around 
`````

The toml file I used 
`````ini
[tool.pytest.ini_options]
elasticsearch_port = 9200
`````

maybe i've missed some breaking change with [elasticsearch-py](https://github.com/elastic/elasticsearch-py)

BTW my requiriement.txt 
`````
pytest==7.4.0
pytest-elasticsearch==4.0.2
python-dotenv==1.0.0
elasticsearch==8.6.2
elasticsearch-dsl>=8.0.0,<9.0.0
`````

**Comment by tsclearcode** [comment]
Hi @maxenva-ext 
I'm not able to reproduce the first issue.
I've tried on:
- 8.12.1 ES server
- elastic-transport==8.12.0
- elasticsearch==8.12.0

Could you provide minimal working example?
